name: Build PilotLight

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release (x86)
        run: |
          msbuild PilotLight/PilotLight.vcxproj /p:Configuration=Release /p:Platform=Win32
        shell: cmd

      - name: Upload EXE (x86)
        uses: actions/upload-artifact@v4
        with:
          name: PilotLight-x86
          path: |
            **/Release/PilotLight.exe
