name: Build PilotLight

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - name: x86
            msbuildPlatform: Win32
          - name: ARM
            msbuildPlatform: ARM

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release (${{ matrix.name }})
        run: |
          msbuild PilotLight/PilotLight.vcxproj /p:Configuration=Release /p:Platform=${{ matrix.msbuildPlatform }}
        shell: cmd

      - name: Upload EXE (${{ matrix.name }})
        uses: actions/upload-artifact@v4
        with:
          name: PilotLight-${{ matrix.name }}
          path: |
            **\\${{ matrix.msbuildPlatform }}\\Release\\PilotLight.exe
