name: Build PilotLight

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - x86
          - ARM

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release (${{ matrix.platform }})
        run: |
          msbuild PilotLight/PilotLight.vcxproj /p:Configuration=Release /p:Platform=${{ matrix.platform }}
        shell: cmd

      - name: Upload EXE (${{ matrix.platform }})
        uses: actions/upload-artifact@v4
        with:
          name: PilotLight-${{ matrix.platform }}
          path: |
            **\${{ matrix.platform }}\Release\PilotLight.exe
